#!/bin/bash

# One-shot setup for Goose + LiteLLM

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${SCRIPT_DIR}/.venv"
GOOSE_CONFIG_DIR="${HOME}/.config/goose"
GOOSE_CONFIG_FILE="${GOOSE_CONFIG_DIR}/config.yaml"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
PYTHON_BIN="/usr/bin/python3"

echo "Setting up Goose with LiteLLM proxy for Bedrock Nova Lite..."

if [ ! -x "${PYTHON_BIN}" ]; then
  echo "Error: ${PYTHON_BIN} not found."
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "Error: curl is required but was not found."
  exit 1
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "Installing uv..."
  curl -LsSf "https://astral.sh/uv/install.sh" | sh
  export PATH="${HOME}/.local/bin:${PATH}"
fi

if ! command -v goose >/dev/null 2>&1; then
  echo "Installing Goose CLI..."
  curl -fsSL "https://github.com/block/goose/releases/download/stable/download_cli.sh" | bash
else
  echo "Goose CLI already installed."
fi

RECREATE_VENV=0
if [ -d "${VENV_DIR}" ]; then
  VENV_PY_VER="$("${VENV_DIR}/bin/python" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || true)"
  if [ -z "${VENV_PY_VER}" ] || [ "${VENV_PY_VER}" = "3.14" ]; then
    RECREATE_VENV=1
  fi
fi

if [ ! -d "${VENV_DIR}" ] || [ "${RECREATE_VENV}" -eq 1 ]; then
  if [ "${RECREATE_VENV}" -eq 1 ]; then
    echo "Recreating .venv with a supported Python version..."
    rm -rf "${VENV_DIR}"
  else
    echo "Creating Python virtual environment..."
  fi
  uv venv --python "${PYTHON_BIN}" "${VENV_DIR}"
fi

echo "Installing LiteLLM dependencies in .venv..."
uv pip install -q --python "${VENV_DIR}/bin/python" "litellm[proxy]" boto3 python-multipart

if [ ! -f "${HOME}/.aws/credentials" ]; then
  echo "Warning: ${HOME}/.aws/credentials not found."
  echo "Run 'aws configure' before making model calls."
else
  echo "AWS credentials file found."
fi

mkdir -p "${GOOSE_CONFIG_DIR}"
if [ -f "${GOOSE_CONFIG_FILE}" ]; then
  cp "${GOOSE_CONFIG_FILE}" "${GOOSE_CONFIG_FILE}.bak.${TIMESTAMP}"
  echo "Backed up existing Goose config to ${GOOSE_CONFIG_FILE}.bak.${TIMESTAMP}"
fi

cat > "${GOOSE_CONFIG_FILE}" <<'EOF'
# Generated by agents-goose/setup.sh
GOOSE_PROVIDER: litellm
GOOSE_MODEL: bedrock-nova-lite
LITELLM_HOST: http://localhost:4321
LITELLM_BASE_PATH: v1/chat/completions
EOF

echo "Wrote Goose config to ${GOOSE_CONFIG_FILE}"
echo ""
echo "Setup complete. Run these commands:"
echo ""
echo "Terminal 1:"
echo "  cd \"${SCRIPT_DIR}\""
echo "  source .venv/bin/activate"
echo "  litellm --config litellm_config.yaml --port 4321"
echo ""
echo "Terminal 2:"
echo "  cd \"${SCRIPT_DIR}\""
echo "  source .venv/bin/activate"
echo "  python goose_server.py"
echo ""
echo "Terminal 3 (example test):"
echo "  cd \"${SCRIPT_DIR}\""
echo "  source .venv/bin/activate"
echo "  python goose_task.py --task \"Write a hello world program in Python\" --wait"